import { EntityType, PartialEntity } from "../api/model";

export const defaultEntity: PartialEntity = {
  name: "Unknown",
  image: "",
  type: EntityType.none,
  build: {
    level: 1,
    attributes: {},
    proficiencies: {},
    abilities: {
      str: 10,
      dex: 10,
      con: 10,
      int: 10,
      wis: 10,
      cha: 10,
    },
    languages: [],
    feats: [],
    specials: [],
    lores: [],
    equipment: [],
    specificProficiencies: {},
    money: {},
    weapons: [],
    armor: [],
    focus: {},
    spellCasters: [],
    formula: [],
    pets: [],
    acTotal: {},
    traits: [],
    resistances: [],
    immunities: [],
  },
  conditions: [],
  damage: 0,
  tempHp: 0,
  initiative: 0,
};
