import { EntityType, PartialEntity } from "../api/model";

export const defaultEntity: PartialEntity = {
  name: "Unknown",
  image: "",
  type: EntityType.none,
  build: {
    level: 1,
    attributes: {},
    proficiencies: {
      classDC: 0,
      perception: 0,
      fortitude: 0,
      reflex: 0,
      will: 0,
      heavy: 0,
      medium: 0,
      light: 0,
      unarmored: 0,
      advanced: 0,
      martial: 0,
      simple: 0,
      unarmed: 0,
      castingArcane: 0,
      castingDivine: 0,
      castingOccult: 0,
      castingPrimal: 0,
      acrobatics: 0,
      arcana: 0,
      athletics: 0,
      crafting: 0,
      deception: 0,
      diplomacy: 0,
      intimidation: 0,
      medicine: 0,
      nature: 0,
      occultism: 0,
      performance: 0,
      religion: 0,
      society: 0,
      stealth: 0,
      survival: 0,
      thievery: 0,
    },
    abilities: {
      str: 10,
      dex: 10,
      con: 10,
      int: 10,
      wis: 10,
      cha: 10,
    },
    languages: [],
    feats: [],
    specials: [],
    lores: [],
    equipment: [],
    specificProficiencies: {},
    money: {},
    weapons: [],
    armor: [],
    focus: {},
    spellCasters: [],
    formula: [],
    pets: [],
    acTotal: {},
    traits: [],
    resistances: [],
    immunities: [],
    actions: {
      actions: [],
      passiveActions: [],
      reactions: [],
      freeActions: [],
    },
  },
  conditions: [],
  damage: 0,
  tempHp: 0,
  initiative: 0,
};
