on:
  pull_request:
    paths:
    - "src-tauri/**"
    branches:
    - main

jobs:
  test_backend:
    name: Testing backend on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: install Rust and cargo
        uses: brndnmtthws/rust-action-rustup@v1

      - name: install node
        uses: actions/setup-node@v3
      - name: npm install and build (needed for tauri)
        run: |
          npm install
          npm run tauri build

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
        if: matrix.os == 'ubuntu-latest'
      - name: run tests
        run: |
          cd src-tauri
          cargo test
